### ISSUE TITLE
TypeError: io.configure is not a function

### ISSUE THREAD

**Issue by isapir** [jgonera/socket.io-multichat#1]
I just realized that this repo is from about 5 years ago, so probably some library updates were not backward compatible.  If there's a quick "fix" for this it'd be great if you can comment on it.

```
> node app
E:\Workspace\node-apps\socket.io-multichat\app.js:13
io.configure(function() {
   ^

TypeError: io.configure is not a function
    at Object.<anonymous> (E:\Workspace\node-apps\socket.io-multichat\app.js:13:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by novenix** [comment]
no fix yet? :( i need how to open a new html with the new joined room :(

**Comment by ankur-sardar** [comment]
It is using old version of socke.io. So try to install an old version 

`$ npm install socket.io@0.9
`

**Comment by risyasin** [comment]
I've added a pull request to run it above socket.io v1
https://github.com/jgonera/socket.io-multichat/pull/2

**Comment by jgonera** [comment]
I'm not sure how this repo got any traction, but I'm sure there are better examples of Socket.IO usage these days :) If you tell me how you found this repo I can try to update that source and archive this repo.
